package com.auto.click.appcomponents.utility

object Contact {
    var FIRST_OPEN_APP = "FIRST_OPEN_APP"
    var OPTION_DELAY_DEFAULT = "OPTION_DELAY_DEFAULT"
    var TIME_DELAY_DEFAULT = "TIME_DELAY_DEFAULT"
    var TIME_SWIPE_DEFAULT = "TIME_SWIPE_DEFAULT"
    var TIME_PRESS_AND_HOLD_DEFAULT = "TIME_PRESS_AND_HOLD_DEFAULT"
    var LIST_CONFIG_SAVE = "LIST_CONFIG_SAVE"
    var LIST_APPLICATION_WITH_CONFIG = "LIST_APPLICATION_WITH_CONFIG"
    var MODE_GAME = "MODE_GAME"
    var MENU_FOLDABLE = "MENU_FOLDABLE"
    var DISPLAY_MENU_HORIZONTAL = "DISPLAY_MENU_HORIZONTAL"
    var DISPLAY_MINI_MENU = "DISPLAY_MINI_MENU"
    var SETTINGS_ANTI_DETECT = "SETTINGS_ANTI_DETECT"
    var SETTINGS_ANTI_DETECT_TIME = "SETTINGS_ANTI_DETECT_TIME"
    var SETTINGS_ANTI_DETECT_POSITIONS = "SETTINGS_ANTI_DETECT_POSITIONS"
    var TARGET_TRANSPARENCY = "TARGET_TRANSPARENCY"
    var TARGET_TRANSPARENCY_PROGRESS = "TARGET_TRANSPARENCY_PROGRESS"
    var TARGET_SIZE = "TARGET_SIZE"
    var MENU_SIZE = "MENU_SIZE"
}
